DELETE FROM stda_calculated_deflections;
DELETE FROM stda_calculations;
DELETE FROM stda_deflections;
DELETE FROM stda_misc;
DELETE FROM stda_moduli_estimated WHERE LONGLIST_ID=2;
DELETE FROM stda_stats WHERE LONGLIST_ID=2;
DELETE FROM STDA_LONGLIST WHERE ID=2;


--SELECT * FROM STDA_LONGLIST;
--SELECT * FROM deflections ORDER BY ID, POINT, DROP_NO ASC;
--SELECT * FROM deflections_calc ORDER BY ID, POINT, DROP_NO ASC;
--SELECT * FROM MOD_EST ORDER BY ID, POINT, DROP_NO ASC;
--SELECT * FROM MISC;
--SELECT * FROM CALC ORDER BY ID, POINT, DROP_NO ASC;
--SELECT * FROM STATS;

SELECT * FROM LONGLIST WHERE ID = 22 OR ID=21;
SELECT * FROM deflections WHERE ID = 22 OR ID=21 ORDER BY ID, POINT, DROP_NO ASC;
SELECT * FROM deflections_calc WHERE ID = 22 OR ID=21 ORDER BY ID, POINT, DROP_NO ASC;
SELECT * FROM MOD_EST WHERE ID = 22 OR ID=21 ORDER BY ID, POINT, DROP_NO ASC;
SELECT * FROM MISC WHERE ID = 22 OR ID=21 ;
SELECT * FROM CALC WHERE ID = 22 OR ID=21 ORDER BY ID, POINT, DROP_NO ASC;
SELECT * FROM STATS WHERE ID = 22 OR ID=21;


SELECT * FROM LONGLIST WHERE ID = 22 OR ID=21;
SELECT * FROM deflections WHERE ID = 22 OR ID=21 ORDER BY ID, POINT, DROP_NO ASC;
SELECT * FROM deflections_calc WHERE ID = 22 OR ID=21 ORDER BY ID, POINT, DROP_NO ASC;
SELECT * FROM MOD_EST WHERE ID = 22 OR ID=21 ORDER BY ID, POINT, DROP_NO ASC;
SELECT * FROM MISC WHERE ID = 22 OR ID=21 ;
SELECT * FROM CALC WHERE ID = 22 OR ID=21 ORDER BY ID, POINT, DROP_NO ASC;
SELECT * FROM STATS WHERE ID = 22 OR ID=21;
SELECT * FROM deflections WHERE ID=2 and drop_no=2;

DROP TRIGGER AUD_STDA_CALCULATIONS;


DELETE FROM stda_calculated_deflections WHERE LONGLIST_ID=2;
DELETE FROM stda_calculations WHERE LONGLIST_ID=2;
DELETE FROM stda_deflections WHERE LONGLIST_ID=2;
DELETE FROM stda_misc WHERE LONGLIST_ID=2;
DELETE FROM stda_moduli_estimated WHERE LONGLIST_ID=2;
DELETE FROM stda_stats WHERE LONGLIST_ID=2;
DELETE FROM STDA_LONGLIST WHERE ID=2;




SELECT ID FROM LONGLIST WHERE LL_NO=185 AND ROUTE='SR-17' AND RP_TO=50.41;

SELECT LOAD FROM DEFLECTIONS  WHERE ID = 1 AND POINT IN (SELECT POINT FROM DEFLECTIONS_CALC WHERE ID = 1) AND DROP_NO IN (SELECT DROP_NO FROM DEFLECTIONS_CALC WHERE ID =1);
SELECT LOAD FROM DEFLECTIONS WHERE ID = 1 AND DROP_NO = 2;
SELECT LOAD FROM DEFLECTIONS  WHERE (ID, POINT, DROP_NO) IN (SELECT ID, POINT, DROP_NO FROM DEFLECTIONS_CALC WHERE ID = 1);
select D1, D2, D3, D4, D5, D6, D7, D8, D9 from deflections WHERE (ID, POINT, DROP_NO) IN (SELECT ID, POINT, DROP_NO FROM DEFLECTIONS_CALC WHERE ID = 1);



SELECT DEFLECTIONS.D1 FROM DEFLECTIONS LEFT JOIN LONGLIST ON DEFLECTIONS.ID = LONGLIST.ID WHERE LONGLIST.REQUEST_NO = 'D2104220001' AND DIR = 'NB';
--SELECT * FROM LONGLIST WHERE DIR = 'SB';

CREATE TABLE STATS(
    id NUMBER,
    COLUMNNAME VARCHAR(20),
    MEAN DOUBLE PRECISION,
    STD DOUBLE PRECISION,
    MAX DOUBLE PRECISION,
    MIN DOUBLE PRECISION
    );
CREATE TABLE CALC(
    id NUMBER,
    POINT NUMBER,
    DROP_NO NUMBER,
    D0 DOUBLE PRECISION,
    D1 DOUBLE PRECISION,
    D2 DOUBLE PRECISION,
    D3 DOUBLE PRECISION,
    D4 DOUBLE PRECISION,
    D5 DOUBLE PRECISION,
    D6 DOUBLE PRECISION,
    D7 DOUBLE PRECISION,
    D8 DOUBLE PRECISION,
    D9 DOUBLE PRECISION,
    LOAD DOUBLE PRECISION,
    STRESS DOUBLE PRECISION,
    SN DOUBLE PRECISION,
    MR DOUBLE PRECISION,
    INSITUCBR DOUBLE PRECISION,
    ASH_ESALS DOUBLE PRECISION,
    IND_ESALS DOUBLE PRECISION,
    LIM_ESALS DOUBLE PRECISION,
    INSITUMR DOUBLE PRECISION,
    LOGSGD DOUBLE PRECISION,
    logmr DOUBLE PRECISION,
    E1 DOUBLE PRECISION,
    E2 DOUBLE PRECISION,
    E3 DOUBLE PRECISION,
    E4 DOUBLE PRECISION
    );
ALTER TABLE STATS ADD CONSTRAINT FK_STATS FOREIGN KEY (ID) REFERENCES LONGLIST(ID);
ALTER TABLE CALC ADD CONSTRAINT FK_CALC FOREIGN KEY (ID) REFERENCES LONGLIST(ID);
DELETE FROM longlist;


DROP TABLE DEFLECTIONS;
DROP TABLE DEFLECTIONS_CALC;
DROP TABLE MOD_EST;
DROP TABLE MISC;
DROP TABLE STATS;
DROP TABLE CALC;
DROP TABLE LONGLIST;