Select stda.stda_longlist_info.request_no as "Request ID", null as "Test Description", stda.stda_Deflections.chainage as "Test DMI", stda.stda_longlist_info.traffic_ctrl as "Test Date", 
CASE WHEN stda.stda_longlist.direction LIKE '%EB%' THEN 'Inc' WHEN stda.stda_longlist.direction LIKE '%NB%' THEN 'Inc' ELSE 'Dec' END As "Travel Direction", null as "Lane_Position_Research", null as "Lane_Position_DTIMS", stda.stda_deflections.gpsx as "Latitude(decimal degrees)", stda.stda_deflections.gpsy as "Longitude(decimal degrees)", null as "Reciever Type", stda.stda_misc.D0_criteria as "Surface Deflection Criteria", stda.stda_misc.subgrade_criteria as "Subgrade Deflection Criteria", 
stda.stda_calculations.deflection_0 as "Surface Deflection", stda.stda_calculations.deflection_8 as "Subgrade Deflection", stda.stda_calculations.insitucbr as "In-Situ CBR", stda.stda_calculations.structural_number as "In-Situ Structure Number",  stda.stda_calculations.insitumr as "Resilient Modulus(corrected)", 
stda.stda_calculations.indot_esals as "Remaining ESALs", stda.stda_calculations.k_value as "K Value", null as "LTE", stda.stda_calculations.elmod_1 as "E1", stda.stda_calculations.elmod_2 as "E2", stda.stda_calculations.elmod_3 as "E3", stda.stda_calculations.elmod_4 as "E4",
stda.stda_deflections.deflection_1 as "D1(uncorrected)", stda.stda_deflections.deflection_2 as "D2(uncorrected)", stda.stda_deflections.deflection_3 as "D3(uncorrected)", stda.stda_deflections.deflection_4 as "D4(uncorrected)", stda.stda_deflections.deflection_5 as "D5(uncorrected)", stda.stda_deflections.deflection_6 as "D6(uncorrected)", stda.stda_deflections.deflection_7 as "D7(uncorrected)", stda.stda_deflections.deflection_8 as "D8(uncorrected)", stda.stda_deflections.deflection_9 as "D9(uncorrected)", stda.stda_deflections.surface_temp as "Surface Temperature(F)", stda.stda_deflections.air_temp as "Air Temperature(F)" 
FROM stda.stda_Deflections INNER JOIN stda.stda_calculations ON stda.stda_Deflections.longlist_id = stda.stda_calculations.longlist_id AND stda.stda_Deflections.point = stda.stda_calculations.point AND stda.stda_Deflections.drop_no = stda.stda_calculations.drop_no
INNER JOIN stda.stda_misc ON stda.stda_misc.longlist_id = stda.stda_calculations.longlist_id
INNER JOIN stda.stda_longlist ON stda.stda_misc.longlist_id = stda.stda_longlist.longlist_id
INNER JOIN stda.stda_longlist_info ON stda.stda_longlist.longlist_no = stda.stda_longlist_info.longlist_no AND stda.stda_longlist.year = stda.stda_longlist_info.year;

select null as "TS Request", stda.stda_longlist.begin_latitude as "Beginning_lat", stda.stda_longlist.begin_longitude as "Beginning_lon", stda.stda_longlist.end_latitude as "Ending_lat", stda.stda_longlist.end_longitude as "Ending_lon", stda.stda_longlist_info.request_no as "Request ID", CASE WHEN stda.stda_longlist.direction LIKE '%EB%' THEN 'Inc' WHEN stda.stda_longlist.direction LIKE '%NB%' THEN 'Inc' ELSE 'Dec' END As "Direction",
null as "Document Name", null as "Test Description"
FROM stda.stda_longlist INNER JOIN stda.stda_longlist_info ON stda.stda_longlist.longlist_no = stda.stda_longlist_info.longlist_no AND stda.stda_longlist.year = stda.stda_longlist_info.year;
